# Created on: Apr 14, 2013
#     Author: jorge
# Waiterbot IR sensors half-ring configuration

filter_buffer_size: 3    # Internal buffers size; use an odd number
ranger_max_reading: 255  # Because sonar readings are unsigned bytes   kkkkkkkkkkkkkk
no_contact_range:  6.0   # Report this distance if no contact; recommended
                         # to use a value similar to the hokuyo max range

# Individual ranger configuration:
#   name:                 Ranger's name (normally its place in the robot)
#   frame_id:             Reference frame id; needed to lookup transform
#   index_fired:          Index that identifies when this sonar is fired
#   index_value:          Index of this sonar in the msg first echo data

rangers:
  - name:        "IR 0 +90"
    frame_id:    "IR0_link"
  - name:        "IR 1 +72"
    frame_id:    "IR1_link"
  - name:        "IR 2 +54"
    frame_id:    "IR2_link"
  - name:        "IR 3 +36"
    frame_id:    "IR3_link"
  - name:        "IR 4 +18"
    frame_id:    "IR4_link"
  - name:        "IR 5 0"
    frame_id:    "IR5_link"
  - name:        "IR 6 -18"
    frame_id:    "IR6_link"
  - name:        "IR 7 -36"
    frame_id:    "IR7_link"
  - name:        "IR 8 -54"
    frame_id:    "IR8_link"
  - name:        "IR 9 -72"
    frame_id:    "IR9_link"
  - name:        "IR 10 -90"
    frame_id:    "IR10_link"

    
como publico los tf???
 - no tf;  calculo con mi codigo
 - robot  xacro  ->>>  tengo que cambiar robot description???  xacro ya estara cargado desde minimal.launch....
 - pub  tf aparte;  lo puedo incluir con el rangers2pc.launch
 
 >>>  necesito algun script para generar valores!!!
 
<!-- Default frames for Kinect/PSDK5 devices
     Places depth and RGB cameras in the same plane with 2.5cm baseline.
     Calibration may improve results, but these defaults are reasonably accurate.
-->
<launch>
  <arg name="camera" default="camera" />

  <arg name="pi/2" value="1.5707963267948966" />
  <arg name="optical_rotate" value="0 0 0 -$(arg pi/2) 0 -$(arg pi/2)" />

  <node pkg="tf" type="static_transform_publisher" name="$(arg camera)_base_link"
        args="0 -0.02  0 0 0 0  /$(arg camera)_link /$(arg camera)_depth_frame 100" />
  <node pkg="tf" type="static_transform_publisher" name="$(arg camera)_base_link1"
        args="0 -0.045 0 0 0 0  /$(arg camera)_link /$(arg camera)_rgb_frame 100" />
  <node pkg="tf" type="static_transform_publisher" name="$(arg camera)_base_link2"
        args="$(arg optical_rotate) /$(arg camera)_depth_frame /$(arg camera)_depth_optical_frame  100" />
  <node pkg="tf" type="static_transform_publisher" name="$(arg camera)_base_link3"
        args="$(arg optical_rotate) /$(arg camera)_rgb_frame /$(arg camera)_rgb_optical_frame 100" />
</launch>
